STD = c++17
openmp1: openmp1.cpp
	g++ -g -Wall -fopenmp -std=$(STD) -o $@ $<

openmp2: openmp2.cpp
	g++ -g -Wall -fopenmp -std=$(STD) -o $@ $<

pointInc: pointInc.cpp
	g++ -g -std=$(STD) -o $@ $<